MatterGen_generate:
  energy_above_hull: 0.05
  batch_size: 100
  num_batches: 3
MatterGen_CSP:
  num_runs: 3
  batch_size: 100
  num_batches: 1
MinimaHopping:
  num_runs: 10
  mh_steps: 30
  fmax: 0.05
bulk_relax:
  fmax: 0.05
  max_steps: 500
face_build:
  fmax: 0.05
  max_steps: 500
  max_miller_idx: 2
  percentage_to_select: 1
adsorbates:
  fmax: 0.05
  max_steps: 500
